LOCALHOST
### Get all contacts
GET http://localhost:3000/contact

 {
    "_id": "68c9b505f6c5388de046cd22",
    "firstName": "Amina",
    "lastName": "Okoye",
    "email": "amina.okoye@example.com",
    "favouriteColor": "Turquoise",
    "birthday": "1992-04-15"
  },
  {
    "_id": "68c9b7bdf6c5388de046cd23",
    "firstName": "David",
    "lastName": "Mensah",
    "email": "david.mensah@example.com",
    "favouriteColor": "Crimson",
    "birthday": "1988-11-02"
  },
  {
    "_id": "68cc50340bd17585f5f5d6a3",
    "firstName": "Chidera",
    "lastName": "Ibrahim",
    "email": "chidera.ibrahim@example.com",
    "favouriteColor": "Emerald",
    "birthday": "1995-07-23"
  }

### Create Contact by ID
GET http://localhost:3000/contact/68cc50340bd17585f5f5d6a3


{
  "_id": "68cc50340bd17585f5f5d6a3",
  "firstName": "Chidera",
  "lastName": "Ibrahim",
  "email": "chidera.ibrahim@example.com",
  "favouriteColor": "Emerald",
  "birthday": "1995-07-23"
}

### Post request to create a new contact
POST http://localhost:3000/contact HTTP/1.1
Content-Type: application/json




###PUT 
PUT http://localhost:3000/contact/68d8692b132774d7ec737c2b
Content-Type: application/json

{
  "firstName": "Bene",
  "lastName": "Ade",
  "email": "ben.ade@example.com",
  "favouriteColor": "Emerald",
  "birthday": "1988-11-23"
}

###DELETE Contact
DELETE http://localhost:3000/contact/68d8692b132774d7ec737c2b HTTP/1.1

PRODUCTION

LOCALHOST
### Get all contacts
GET https://cse341-project-ghpc.onrender.com/contact

 {
    "_id": "68c9b505f6c5388de046cd22",
    "firstName": "Amina",
    "lastName": "Okoye",
    "email": "amina.okoye@example.com",
    "favouriteColor": "Turquoise",
    "birthday": "1992-04-15"
  },
  {
    "_id": "68c9b7bdf6c5388de046cd23",
    "firstName": "David",
    "lastName": "Mensah",
    "email": "david.mensah@example.com",
    "favouriteColor": "Crimson",
    "birthday": "1988-11-02"
  },
  {
    "_id": "68cc50340bd17585f5f5d6a3",
    "firstName": "Chidera",
    "lastName": "Ibrahim",
    "email": "chidera.ibrahim@example.com",
    "favouriteColor": "Emerald",
    "birthday": "1995-07-23"
  }

### Create Contact by ID
GET https://cse341-project-ghpc.onrender.com/68cc50340bd17585f5f5d6a3


{
  "_id": "68cc50340bd17585f5f5d6a3",
  "firstName": "Chidera",
  "lastName": "Ibrahim",
  "email": "chidera.ibrahim@example.com",
  "favouriteColor": "Emerald",
  "birthday": "1995-07-23"
}

### Post request to create a new contact
POST https://cse341-project-ghpc.onrender.com/contact HTTP/1.1
Content-Type: application/json


{
   "firstName": "Benedict",
    "lastName": "Adelakun",
    "email": "benedict.adelakun@example.com",
    "favouriteColor": "Emerald",
    "birthday": "1988-11-23"
}



###PUT 
PUT https://cse341-project-ghpc.onrender.com/contact/ HTTP/1.1
Content-Type: application/json

{
  "firstName": "Bene",
  "lastName": "Ade",
  "email": "ben.ade@example.com",
  "favouriteColor": "Emerald",
  "birthday": "1988-11-23"
}

###DELETE Contact
DELETE https://cse341-project-ghpc.onrender.com/contact/ HTTP/1.1

